[server]
allow-cors = true
host = "localhost"
port = 5555
grid-url = "https://172.31.27.218:4444"
[[node.driver-configuration]]
max-sessions = 20
display-name = "OSX Firefox Latest"
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"latest\", \"platformName\": \"mac\", \"moz:firefoxOptions\": {\"binary\": \"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin\"}}"
[[node.driver-configuration]]
max-sessions = 20
display-name = "OSX Chrome Latest"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"latest\", \"platformName\": \"mac\", \"goog:chromeOptions\": {\"binary\": \"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome\"}}"
